-- MySQL Script generated by MySQL Workbench
-- Fri Aug 10 15:23:17 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gofar-travel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gofar-travel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gofar-travel` DEFAULT CHARACTER SET utf8 ;
USE `gofar-travel` ;

-- -----------------------------------------------------
-- Table `gofar-travel`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Options` (
  `idOptions` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`idOptions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Optionnal equipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Optionnal equipement` (
  `idOptionnal equipement` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `cost` INT NOT NULL,
  PRIMARY KEY (`idOptionnal equipement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Model` (
  `idModel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`state of vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`state of vehicles` (
  `idstate of vehicles` INT NOT NULL AUTO_INCREMENT,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstate of vehicles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Vehicles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Vehicles` (
  `idVehicles` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `cost` VARCHAR(45) NOT NULL,
  `Model_idModel` INT NOT NULL,
  `Options_idOptions` INT NOT NULL,
  `state of vehicles_idstate of vehicles` INT NOT NULL,
  PRIMARY KEY (`idVehicles`, `Model_idModel`, `Options_idOptions`, `state of vehicles_idstate of vehicles`),
  INDEX `fk_Vehicles_Model1_idx` (`Model_idModel` ASC),
  INDEX `fk_Vehicles_Options1_idx` (`Options_idOptions` ASC),
  INDEX `fk_Vehicles_state of vehicles1_idx` (`state of vehicles_idstate of vehicles` ASC),
  CONSTRAINT `fk_Vehicles_Model1`
    FOREIGN KEY (`Model_idModel`)
    REFERENCES `gofar-travel`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicles_Options1`
    FOREIGN KEY (`Options_idOptions`)
    REFERENCES `gofar-travel`.`Options` (`idOptions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehicles_state of vehicles1`
    FOREIGN KEY (`state of vehicles_idstate of vehicles`)
    REFERENCES `gofar-travel`.`state of vehicles` (`idstate of vehicles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Salesperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Salesperson` (
  `idSalesperson` INT NOT NULL AUTO_INCREMENT,
  `phone number` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  PRIMARY KEY (`idSalesperson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Adresses` (
  `idAdresses` INT NOT NULL AUTO_INCREMENT,
  `number` TINYINT(10) NOT NULL,
  `street` VARCHAR(75) NOT NULL,
  `zipcode` INT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdresses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `phone number` INT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Recovery vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Recovery vehicle` (
  `idRecovery vehicle` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `cost` VARCHAR(45) NOT NULL,
  `Model_idModel` INT NOT NULL,
  `Options_idOptions` INT NOT NULL,
  PRIMARY KEY (`idRecovery vehicle`, `Model_idModel`, `Options_idOptions`),
  INDEX `fk_Recovery vehicle_Model1_idx` (`Model_idModel` ASC),
  INDEX `fk_Recovery vehicle_Options1_idx` (`Options_idOptions` ASC),
  CONSTRAINT `fk_Recovery vehicle_Model1`
    FOREIGN KEY (`Model_idModel`)
    REFERENCES `gofar-travel`.`Model` (`idModel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recovery vehicle_Options1`
    FOREIGN KEY (`Options_idOptions`)
    REFERENCES `gofar-travel`.`Options` (`idOptions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Taxes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Taxes` (
  `idTaxes` INT NOT NULL AUTO_INCREMENT,
  `amount taxe` TINYINT(3) NOT NULL,
  PRIMARY KEY (`idTaxes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Invoices` (
  `idInvoices` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `Total amount` INT NOT NULL,
  `Salesperson_idSalesperson` INT NOT NULL,
  `Customers_idCustomers` INT NOT NULL,
  `Recovery vehicle_idRecovery vehicle` INT NOT NULL,
  `Taxes_idTaxes` INT NOT NULL,
  `Vehicles_idVehicles` INT NOT NULL,
  PRIMARY KEY (`idInvoices`, `Salesperson_idSalesperson`, `Customers_idCustomers`, `Recovery vehicle_idRecovery vehicle`, `Taxes_idTaxes`, `Vehicles_idVehicles`),
  INDEX `fk_Invoices_Salesperson1_idx` (`Salesperson_idSalesperson` ASC),
  INDEX `fk_Invoices_Customers1_idx` (`Customers_idCustomers` ASC),
  INDEX `fk_Invoices_Recovery vehicle1_idx` (`Recovery vehicle_idRecovery vehicle` ASC),
  INDEX `fk_Invoices_Taxes1_idx` (`Taxes_idTaxes` ASC),
  INDEX `fk_Invoices_Vehicles1_idx` (`Vehicles_idVehicles` ASC),
  CONSTRAINT `fk_Invoices_Salesperson1`
    FOREIGN KEY (`Salesperson_idSalesperson`)
    REFERENCES `gofar-travel`.`Salesperson` (`idSalesperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `gofar-travel`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Recovery vehicle1`
    FOREIGN KEY (`Recovery vehicle_idRecovery vehicle`)
    REFERENCES `gofar-travel`.`Recovery vehicle` (`idRecovery vehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Taxes1`
    FOREIGN KEY (`Taxes_idTaxes`)
    REFERENCES `gofar-travel`.`Taxes` (`idTaxes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Invoices_Vehicles1`
    FOREIGN KEY (`Vehicles_idVehicles`)
    REFERENCES `gofar-travel`.`Vehicles` (`idVehicles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Salesperson_has_Adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Salesperson_has_Adresses` (
  `Salesperson_idSalesperson` INT NOT NULL,
  `Adresses_idAdresses` INT NOT NULL,
  PRIMARY KEY (`Salesperson_idSalesperson`, `Adresses_idAdresses`),
  INDEX `fk_Salesperson_has_Adresses_Adresses1_idx` (`Adresses_idAdresses` ASC),
  INDEX `fk_Salesperson_has_Adresses_Salesperson_idx` (`Salesperson_idSalesperson` ASC),
  CONSTRAINT `fk_Salesperson_has_Adresses_Salesperson`
    FOREIGN KEY (`Salesperson_idSalesperson`)
    REFERENCES `gofar-travel`.`Salesperson` (`idSalesperson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Salesperson_has_Adresses_Adresses1`
    FOREIGN KEY (`Adresses_idAdresses`)
    REFERENCES `gofar-travel`.`Adresses` (`idAdresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Customers_has_Adresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Customers_has_Adresses` (
  `Customers_idCustomers` INT NOT NULL,
  `Adresses_idAdresses` INT NOT NULL,
  PRIMARY KEY (`Customers_idCustomers`, `Adresses_idAdresses`),
  INDEX `fk_Customers_has_Adresses_Adresses1_idx` (`Adresses_idAdresses` ASC),
  INDEX `fk_Customers_has_Adresses_Customers1_idx` (`Customers_idCustomers` ASC),
  CONSTRAINT `fk_Customers_has_Adresses_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `gofar-travel`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customers_has_Adresses_Adresses1`
    FOREIGN KEY (`Adresses_idAdresses`)
    REFERENCES `gofar-travel`.`Adresses` (`idAdresses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`Optionnal equipement_has_Invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`Optionnal equipement_has_Invoices` (
  `Optionnal equipement_idOptionnal equipement` INT NOT NULL,
  `Invoices_idInvoices` INT NOT NULL,
  PRIMARY KEY (`Optionnal equipement_idOptionnal equipement`, `Invoices_idInvoices`),
  INDEX `fk_Optionnal equipement_has_Invoices_Invoices1_idx` (`Invoices_idInvoices` ASC),
  INDEX `fk_Optionnal equipement_has_Invoices_Optionnal equipement1_idx` (`Optionnal equipement_idOptionnal equipement` ASC),
  CONSTRAINT `fk_Optionnal equipement_has_Invoices_Optionnal equipement1`
    FOREIGN KEY (`Optionnal equipement_idOptionnal equipement`)
    REFERENCES `gofar-travel`.`Optionnal equipement` (`idOptionnal equipement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Optionnal equipement_has_Invoices_Invoices1`
    FOREIGN KEY (`Invoices_idInvoices`)
    REFERENCES `gofar-travel`.`Invoices` (`idInvoices`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gofar-travel`.`warehouse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gofar-travel`.`warehouse` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `Recovery vehicle_idRecovery vehicle` INT NOT NULL,
  `Vehicles_idVehicles` INT NOT NULL,
  PRIMARY KEY (`idtable1`, `Recovery vehicle_idRecovery vehicle`, `Vehicles_idVehicles`),
  INDEX `fk_table1_Recovery vehicle1_idx` (`Recovery vehicle_idRecovery vehicle` ASC),
  INDEX `fk_warehouse_Vehicles1_idx` (`Vehicles_idVehicles` ASC),
  CONSTRAINT `fk_table1_Recovery vehicle1`
    FOREIGN KEY (`Recovery vehicle_idRecovery vehicle`)
    REFERENCES `gofar-travel`.`Recovery vehicle` (`idRecovery vehicle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_warehouse_Vehicles1`
    FOREIGN KEY (`Vehicles_idVehicles`)
    REFERENCES `gofar-travel`.`Vehicles` (`idVehicles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
